name:                bot
version:             0.1.0.0
github:              "LyuPo7/bot"
license:             BSD3
author:              "LyuPo"
maintainer:          "lport@frtk.ru"
copyright:           "2021 LyuPo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bot#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- http-types
- http-client-tls
- http-client
- bytestring
- text
- lens
- lens-aeson
- aeson
- HDBC >=2.4
- HDBC-sqlite3 >= 2.3.3.0
- directory
- http-api-data
- transformers
- time
- hformat
- data-default
- mtl
- containers
- text-show
- utf8-string
- hspec
- exceptions
- filepath
- transformers-either
- convertible

default-extensions: OverloadedStrings

library:
  source-dirs: src
  ghc-options: 
    - -Wall 
    - -Werror

executables:
  bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options: 
    - -Wall 
    - -Werror 
    - -threaded 
    - -rtsopts 
    - -with-rtsopts=-N
    dependencies:
    - bot
    - http-conduit
    - http-types
    - http-client-tls
    - http-client
    - bytestring
    - text
    - lens
    - lens-aeson
    - aeson
    - HDBC >=2.4
    - HDBC-sqlite3 >= 2.3.3.0

tests:
  bot-test:
    main:                Test.hs
    source-dirs:         test
    other-modules: [
      TestBot.Config,
      TestBot.Request.Request,
      TestBot.Mode.Mode,
      TestBot.Api.Tele.Parser.Parser,
      TestBot.Api.Vk.Parser.Parser,
      TestBot.Api.Vk.GenData,
      TestBot.Api.Vk.Handlers,
      TestBot.Api.Tele.GenData,
      TestBot.Api.Tele.Handlers,
      TestBot.Handlers,
      TestBot.GenData
      ]
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
    - hspec
    - tasty
    - tasty-hspec
    - tasty-hedgehog
    - hedgehog >= 0.5 && < 1.1
    - tasty-golden
